job("first-maven-project-by-DSL") {
    description("first maven job generated by the DSL on ${new Date()}")

    scm {
        git("https://github.com/danialkarim807/maven.git", "*/main")
    }

    triggers {
        scm("* * * * *")
    }

    steps {

        maven("clean package", "pom.xml")
    }

    publishers {
        archiveArtifacts "**/*.jar"
    }
}





https://github.com/danialkarim807/maven.git/